### PR TITLE
Add links to DESCRIPTION

### PR DESCRIPTION
**Pull request by olivroy**
You may also consider adding the website link in the about section of the github homepage!

### CODE REVIEW

**Review by JosiahParry — COMMENTED** [review]
Nice!

**Comment by olivroy** [comment]
Thanks for merging! I meant to add the website link here too
image

**Comment by JosiahParry** [comment]
Got it! Thank you!

**Comment by olivroy** [comment]
and also, an fyi, when creating a new package, `usethis::use_pkgdown_github_pages()` does all this automatically (initiate a pkgdown site, add links to DESCRIPTION + the gh homepage) 

There is also `usethis::use_github_links()` that automatically updates DESCRIPTION

**Comment by JosiahParry** [comment]
Good to know! I typically avoid a fair bit of the usethis scaffolding after being bitten a few too many times!

**Pull request merged**
